name: Dummy Workflow

on:
  push:
    branches:
      - '**'

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "Welcome to GitHub Actions!"
      - name: List files
        run: ls -a
  good_bye:
    needs: welcome
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye message
        run: echo "Goodbye from GitHub Actions!"